add_library(ijksdl SHARED
    ijksdl_aout.c
    ijksdl_audio.c
    ijksdl_egl.c
    ijksdl_error.c
    ijksdl_mutex.c
    ijksdl_stdinc.c
    ijksdl_thread.c
    ijksdl_timer.c
    ijksdl_vout.c
    ijksdl_extra_log.c
    gles2/color.c
    gles2/common.c
    gles2/renderer.c
    gles2/renderer_rgb.c
    gles2/renderer_yuv420p.c
    gles2/renderer_yuv444p10le.c
    gles2/shader.c
    gles2/fsh/rgb.fsh.c
    gles2/fsh/yuv420p.fsh.c
    gles2/fsh/yuv444p10le.fsh.c
    gles2/vsh/mvp.vsh.c
    dummy/ijksdl_vout_dummy.c
    ffmpeg/ijksdl_vout_overlay_ffmpeg.c
    ffmpeg/abi_all/image_convert.c
    android/android_audiotrack.c
    android/android_nativewindow.c
    android/ijksdl_android_jni.c
    android/ijksdl_aout_android_audiotrack.c
    android/ijksdl_aout_android_opensles.c
    android/ijksdl_codec_android_mediacodec_dummy.c
    android/ijksdl_codec_android_mediacodec_internal.c
    android/ijksdl_codec_android_mediacodec_java.c
    android/ijksdl_codec_android_mediacodec.c
    android/ijksdl_codec_android_mediadef.c
    android/ijksdl_codec_android_mediaformat_java.c
    android/ijksdl_codec_android_mediaformat.c
    android/ijksdl_vout_android_nativewindow.c
    android/ijksdl_vout_android_surface.c
    android/ijksdl_vout_overlay_android_mediacodec.c
)

target_include_directories(ijksdl PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/..
    ${IJK_FFMPEG_INCLUDE_PATH}
    ${CMAKE_CURRENT_SOURCE_DIR}/../ijkj4a
)

target_link_libraries(ijksdl
    PRIVATE
        ijkffmpeg
        yuv_static
        ijkj4a
        cpufeatures
        log
        android
        OpenSLES
        EGL
        GLESv2
)
