# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# AndroidX is mandatory under AGP 8
android.useAndroidX=true
android.nonTransitiveRClass=true

VERSION_NAME=0.8.8
VERSION_CODE=800800
GROUP=tv.danmaku.ijk.media

# http://central.sonatype.org/pages/requirements.html
POM_USER_ORG=bilibili
POM_DESCRIPTION=Video player based on FFmpeg
POM_URL=https://github.com/Bilibili/ijkplayer
POM_SCM_URL=https://github.com/Bilibili/ijkplayer
POM_SCM_CONNECTION=scm:git:git@github.com:Bilibili/ijkplayer.git
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:Bilibili/ijkplayer.git
POM_LICENSE_NAME=LGPL-2.1
POM_LICENSE_URL=https://www.gnu.org/licenses/lgpl-2.1.html
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=bbcallen
POM_DEVELOPER_NAME=Zhang Rui
POM_DEVELOPER_EMAIL=bbcallen@gmail.com
